export const textos = {
  es: {idioma: "es",
    // Menú
    inicio: "Inicio",
    programa: "Programa",
    lugar: "Lugar",
    menu: "Menú",
    transporte: "Transporte",
    confirmacion: "Asistencia",
    regalo: "Regalo",
    galeria: "Fotos",
    mensajes: "Mensajes",
    reto: "Reto",
    ruleta: "Ruleta",
    sorteo: "Sorteo",

    // Inicio
    nosCasamos: "NOS CASAMOS",
    fecha: "Sábado, 22 de mayo de 2027",
    ceremonia: "Ceremonia a las 18:00 h",
    dias: "días",
    horas: "horas",
    minutos: "minutos",
    segundos: "segundos",

    // Lugar
    dondeCelebramos: "DÓNDE CELEBRAMOS",
    abrirMaps: "Abrir en Google Maps",
    autobusInvitados: "AUTOBÚS PARA INVITADOS",
    ida: "IDA",
    vuelta: "VUELTA",
    autobusTexto: "Salida desde la estación de Plaza Castilla. Apúntate al confirmar asistencia.",

    // Confirmacion
    confirmaAsistencia: "CONFIRMA TU ASISTENCIA",
    vienesBoda: "¿Venís a la boda?",
    limiteConfirmar: "Antes del 1 de marzo de 2027",
    tuNombre: "TU NOMBRE",
    nombreApellidos: "Nombre y apellidos",
    acompanantes: "ACOMPAÑANTES",
    cuantosVenis: "¿Cuántas personas venís en total? (sin contarte a ti)",
    soloYo: "Solo yo",
    autobus: "AUTOBÚS",
    alergias: "ALERGIAS E INTOLERANCIAS",
    alergiasPlaceholder: "Ej: Pedro es alérgico a los frutos secos...",
    platoPrincipal: "PLATO PRINCIPAL",
    platoTexto: "¿Qué preferís para el plato principal?",
    carne: "🥩 Carne",
    pescado: "🐟 Pescado",
    menuEspecial: "🥗 Menú especial (sin carne ni pescado)",
    mesa: "TU MESA",
    mesaTexto: "Te comunicaremos el número de mesa cuando tengamos el seating plan listo. 🤍",
    confirmarBtn: "Confirmar asistencia 🤍",
    graciasMensaje: "¡Gracias! Hemos recibido tu confirmación. ¡Estamos deseando celebrarlo con vosotros! 🤍",

    // Regalo
    vuestraAportacion: "VUESTRA APORTACIÓN",
    regalo: "Regalo",
    mensajeRegalo: "Recordad: lo importante es que vengáis con ilusión, alegría y ganas de pasarlo bien. Pero si queréis hacernos un regalo...",
    lunaDeHiel: "¡Sumad kilómetros a nuestra luna de miel! 🌙",
    transferencia: "TRANSFERENCIA BANCARIA",
    concepto: "CONCEPTO OBLIGATORIO",
    copiarIBAN: "Copiar IBAN",
    copiarConcepto: "Copiar concepto",
    copiarNumero: "Copiar número",
    copiado: "¡Copiado! ✓",
    departe: "¿DE PARTE DE QUIÉN?",
    departeTexto: "Indica tu nombre para que podamos saber de quién es el regalo 🤍",
    guardarNombre: "Guardar mi nombre",

    // Galería
    compartidMomentos: "COMPARTID VUESTROS MOMENTOS",
    galeriaFotos: "Galería de fotos",
    subidFotos: "Subid vuestras fotos favoritas de la boda 📷",
    subirFotos: "📷 Subir fotos",
    subiendoFotos: "Subiendo fotos... ⏳",
    sinFotos: "Aún no hay fotos. ¡Sé el primero en subir una!",

    // Mensajes
    dejadPalabras: "DEJADNOS VUESTRAS PALABRAS",
    muroPalabras: "Muro de mensajes",
    escribeMensaje: "ESCRIBE TU MENSAJE",
    tuMensaje: "Escribe tu felicitación, deseo o mensaje para los novios...",
    enviarMensaje: "Enviar mensaje 💬",
    enviando: "Enviando... ⏳",
    sinMensajes: "Aún no hay mensajes. ¡Sé el primero en escribir!",

    // Reto
    retoFotos: "Reto de fotos",
    retoDescripcion: "Completa al menos 3 misiones antes de las 22:00 h y participa en el sorteo 🏆",
    misionesCompletadas: "misiones completadas",
    tuNombreReto: "TU NOMBRE",
    escribeNombreReto: "Escribe tu nombre para participar",
    subirFoto: "📷 Subir foto",
    misionCompletada: "✓ ¡Misión completada!",
    participasSorteo: "¡Ya participas en el sorteo!",
    tiempoAgotado: "⏰ El tiempo para completar los retos ha terminado. ¡Gracias por participar!",

    // Ruleta
    juego: "JUEGO",
    ruletaActividades: "Ruleta de actividades",
    ruletaDescripcion: "¡Gira la ruleta y haz lo que te toque! 🎡",
    girar: "¡Girar! 🎡",
    girando: "Girando... 🎡",
    ultimasActividades: "ÚLTIMAS ACTIVIDADES",
  },

  en: {idioma: "en",
    // Menu
    inicio: "Home",
    programa: "Schedule",
    lugar: "Venue",
    menu: "Menu",
    transporte: "Transport",
    confirmacion: "RSVP",
    regalo: "Gift",
    galeria: "Photos",
    mensajes: "Messages",
    reto: "Challenge",
    ruleta: "Wheel",
    sorteo: "Draw",

    // Home
    nosCasamos: "WE'RE GETTING MARRIED",
    fecha: "Saturday, 22nd May 2027",
    ceremonia: "Ceremony at 6:00 PM",
    dias: "days",
    horas: "hours",
    minutos: "minutes",
    segundos: "seconds",

    // Venue
    dondeCelebramos: "WHERE WE CELEBRATE",
    abrirMaps: "Open in Google Maps",
    autobusInvitados: "SHUTTLE BUS FOR GUESTS",
    ida: "OUTBOUND",
    vuelta: "RETURN",
    autobusTexto: "Departure from Plaza Castilla station. Sign up when confirming attendance.",

    // Confirmation
    confirmaAsistencia: "CONFIRM YOUR ATTENDANCE",
    vienesBoda: "Will you join us?",
    limiteConfirmar: "Before 1st March 2027",
    tuNombre: "YOUR NAME",
    nombreApellidos: "Full name",
    acompanantes: "GUESTS",
    cuantosVenis: "How many people in your group? (not counting yourself)",
    soloYo: "Just me",
    autobus: "SHUTTLE BUS",
    alergias: "ALLERGIES & INTOLERANCES",
    alergiasPlaceholder: "E.g: Peter is allergic to nuts...",
    platoPrincipal: "MAIN COURSE",
    platoTexto: "What would you prefer for the main course?",
    carne: "🥩 Meat",
    pescado: "🐟 Fish",
    menuEspecial: "🥗 Special menu (no meat or fish)",
    mesa: "YOUR TABLE",
    mesaTexto: "We will let you know your table number once the seating plan is ready. 🤍",
    confirmarBtn: "Confirm attendance 🤍",
    graciasMensaje: "Thank you! We've received your confirmation. We can't wait to celebrate with you! 🤍",

    // Gift
    vuestraAportacion: "YOUR CONTRIBUTION",
    regalo: "Gift",
    mensajeRegalo: "Remember: the most important thing is that you come with excitement, joy and good vibes. But if you'd like to give us a gift...",
    lunaDeHiel: "Help us add miles to our honeymoon! 🌙",
    transferencia: "BANK TRANSFER",
    concepto: "MANDATORY REFERENCE",
    copiarIBAN: "Copy IBAN",
    copiarConcepto: "Copy reference",
    copiarNumero: "Copy number",
    copiado: "Copied! ✓",
    departe: "FROM WHOM?",
    departeTexto: "Write your name so we know who the gift is from 🤍",
    guardarNombre: "Save my name",

    // Gallery
    compartidMomentos: "SHARE YOUR MOMENTS",
    galeriaFotos: "Photo gallery",
    subidFotos: "Upload your favourite photos from the wedding 📷",
    subirFotos: "📷 Upload photos",
    subiendoFotos: "Uploading... ⏳",
    sinFotos: "No photos yet. Be the first to upload one!",

    // Messages
    dejadPalabras: "LEAVE US YOUR WORDS",
    muroPalabras: "Message wall",
    escribeMensaje: "WRITE YOUR MESSAGE",
    tuMensaje: "Write your wishes or message for the newlyweds...",
    enviarMensaje: "Send message 💬",
    enviando: "Sending... ⏳",
    sinMensajes: "No messages yet. Be the first to write one!",

    // Challenge
    retoFotos: "Photo challenge",
    retoDescripcion: "Complete at least 3 missions before 10:00 PM and enter the prize draw 🏆",
    misionesCompletadas: "missions completed",
    tuNombreReto: "YOUR NAME",
    escribeNombreReto: "Write your name to participate",
    subirFoto: "📷 Upload photo",
    misionCompletada: "✓ Mission complete!",
    participasSorteo: "You're in the prize draw!",
    tiempoAgotado: "⏰ Time's up! Thanks for participating!",

    // Wheel
    juego: "GAME",
    ruletaActividades: "Activity wheel",
    ruletaDescripcion: "Spin the wheel and do what you get! 🎡",
    girar: "Spin! 🎡",
    girando: "Spinning... 🎡",
    ultimasActividades: "LAST ACTIVITIES",
  }
};